#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodN_WebService
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="FoodN_DB")]
	public partial class DataClassesFoodNDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertChiTietDichVu(ChiTietDichVu instance);
    partial void UpdateChiTietDichVu(ChiTietDichVu instance);
    partial void DeleteChiTietDichVu(ChiTietDichVu instance);
    partial void InsertCuaHang(CuaHang instance);
    partial void UpdateCuaHang(CuaHang instance);
    partial void DeleteCuaHang(CuaHang instance);
    partial void InsertDanhGia(DanhGia instance);
    partial void UpdateDanhGia(DanhGia instance);
    partial void DeleteDanhGia(DanhGia instance);
    partial void InsertDichVu(DichVu instance);
    partial void UpdateDichVu(DichVu instance);
    partial void DeleteDichVu(DichVu instance);
    partial void InsertFoodN_User(FoodN_User instance);
    partial void UpdateFoodN_User(FoodN_User instance);
    partial void DeleteFoodN_User(FoodN_User instance);
    partial void InsertMenu(Menu instance);
    partial void UpdateMenu(Menu instance);
    partial void DeleteMenu(Menu instance);
    partial void InsertMonAn(MonAn instance);
    partial void UpdateMonAn(MonAn instance);
    partial void DeleteMonAn(MonAn instance);
    partial void InsertYeuThich(YeuThich instance);
    partial void UpdateYeuThich(YeuThich instance);
    partial void DeleteYeuThich(YeuThich instance);
    partial void InsertViTri(ViTri instance);
    partial void UpdateViTri(ViTri instance);
    partial void DeleteViTri(ViTri instance);
    #endregion
		
		public DataClassesFoodNDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["FoodN_DBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesFoodNDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesFoodNDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesFoodNDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesFoodNDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ChiTietDichVu> ChiTietDichVus
		{
			get
			{
				return this.GetTable<ChiTietDichVu>();
			}
		}
		
		public System.Data.Linq.Table<CuaHang> CuaHangs
		{
			get
			{
				return this.GetTable<CuaHang>();
			}
		}
		
		public System.Data.Linq.Table<DanhGia> DanhGias
		{
			get
			{
				return this.GetTable<DanhGia>();
			}
		}
		
		public System.Data.Linq.Table<DichVu> DichVus
		{
			get
			{
				return this.GetTable<DichVu>();
			}
		}
		
		public System.Data.Linq.Table<FoodN_User> FoodN_Users
		{
			get
			{
				return this.GetTable<FoodN_User>();
			}
		}
		
		public System.Data.Linq.Table<Menu> Menus
		{
			get
			{
				return this.GetTable<Menu>();
			}
		}
		
		public System.Data.Linq.Table<MonAn> MonAns
		{
			get
			{
				return this.GetTable<MonAn>();
			}
		}
		
		public System.Data.Linq.Table<YeuThich> YeuThiches
		{
			get
			{
				return this.GetTable<YeuThich>();
			}
		}
		
		public System.Data.Linq.Table<ViTri> ViTris
		{
			get
			{
				return this.GetTable<ViTri>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietDichVu")]
	public partial class ChiTietDichVu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_DichVu;
		
		private string _TenDichVu;
		
		private EntitySet<DichVu> _DichVus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_DichVuChanging(int value);
    partial void OnID_DichVuChanged();
    partial void OnTenDichVuChanging(string value);
    partial void OnTenDichVuChanged();
    #endregion
		
		public ChiTietDichVu()
		{
			this._DichVus = new EntitySet<DichVu>(new Action<DichVu>(this.attach_DichVus), new Action<DichVu>(this.detach_DichVus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DichVu", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_DichVu
		{
			get
			{
				return this._ID_DichVu;
			}
			set
			{
				if ((this._ID_DichVu != value))
				{
					this.OnID_DichVuChanging(value);
					this.SendPropertyChanging();
					this._ID_DichVu = value;
					this.SendPropertyChanged("ID_DichVu");
					this.OnID_DichVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDichVu", DbType="NVarChar(50)")]
		public string TenDichVu
		{
			get
			{
				return this._TenDichVu;
			}
			set
			{
				if ((this._TenDichVu != value))
				{
					this.OnTenDichVuChanging(value);
					this.SendPropertyChanging();
					this._TenDichVu = value;
					this.SendPropertyChanged("TenDichVu");
					this.OnTenDichVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChiTietDichVu_DichVu", Storage="_DichVus", ThisKey="ID_DichVu", OtherKey="ID_DichVu")]
		internal EntitySet<DichVu> DichVus
		{
			get
			{
				return this._DichVus;
			}
			set
			{
				this._DichVus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DichVus(DichVu entity)
		{
			this.SendPropertyChanging();
			entity.ChiTietDichVu = this;
		}
		
		private void detach_DichVus(DichVu entity)
		{
			this.SendPropertyChanging();
			entity.ChiTietDichVu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CuaHang")]
	public partial class CuaHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_CuaHang;
		
		private string _TenCuaHang;
		
		private string _DiaChi;
		
		private string _GioMoCua;
		
		private string _GioDongCua;
		
		private byte[] _HinhAnh;
		
		private string _SDT_CuaHang;
		
		private string _TenNhom;
		
		private EntitySet<DanhGia> _DanhGias;
		
		private EntitySet<DichVu> _DichVus;
		
		private EntitySet<Menu> _Menus;
		
		private EntitySet<YeuThich> _YeuThiches;
		
		private EntityRef<ViTri> _ViTri;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_CuaHangChanging(int value);
    partial void OnID_CuaHangChanged();
    partial void OnTenCuaHangChanging(string value);
    partial void OnTenCuaHangChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnGioMoCuaChanging(string value);
    partial void OnGioMoCuaChanged();
    partial void OnGioDongCuaChanging(string value);
    partial void OnGioDongCuaChanged();
    partial void OnHinhAnhChanging(byte[] value);
    partial void OnHinhAnhChanged();
    partial void OnSDT_CuaHangChanging(string value);
    partial void OnSDT_CuaHangChanged();
    partial void OnTenNhomChanging(string value);
    partial void OnTenNhomChanged();
    #endregion
		
		public CuaHang()
		{
			this._DanhGias = new EntitySet<DanhGia>(new Action<DanhGia>(this.attach_DanhGias), new Action<DanhGia>(this.detach_DanhGias));
			this._DichVus = new EntitySet<DichVu>(new Action<DichVu>(this.attach_DichVus), new Action<DichVu>(this.detach_DichVus));
			this._Menus = new EntitySet<Menu>(new Action<Menu>(this.attach_Menus), new Action<Menu>(this.detach_Menus));
			this._YeuThiches = new EntitySet<YeuThich>(new Action<YeuThich>(this.attach_YeuThiches), new Action<YeuThich>(this.detach_YeuThiches));
			this._ViTri = default(EntityRef<ViTri>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CuaHang", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_CuaHang
		{
			get
			{
				return this._ID_CuaHang;
			}
			set
			{
				if ((this._ID_CuaHang != value))
				{
					this.OnID_CuaHangChanging(value);
					this.SendPropertyChanging();
					this._ID_CuaHang = value;
					this.SendPropertyChanged("ID_CuaHang");
					this.OnID_CuaHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenCuaHang", DbType="NVarChar(50)")]
		public string TenCuaHang
		{
			get
			{
				return this._TenCuaHang;
			}
			set
			{
				if ((this._TenCuaHang != value))
				{
					this.OnTenCuaHangChanging(value);
					this.SendPropertyChanging();
					this._TenCuaHang = value;
					this.SendPropertyChanged("TenCuaHang");
					this.OnTenCuaHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(100)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioMoCua", DbType="Char(6)")]
		public string GioMoCua
		{
			get
			{
				return this._GioMoCua;
			}
			set
			{
				if ((this._GioMoCua != value))
				{
					this.OnGioMoCuaChanging(value);
					this.SendPropertyChanging();
					this._GioMoCua = value;
					this.SendPropertyChanged("GioMoCua");
					this.OnGioMoCuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioDongCua", DbType="Char(6)")]
		public string GioDongCua
		{
			get
			{
				return this._GioDongCua;
			}
			set
			{
				if ((this._GioDongCua != value))
				{
					this.OnGioDongCuaChanging(value);
					this.SendPropertyChanging();
					this._GioDongCua = value;
					this.SendPropertyChanged("GioDongCua");
					this.OnGioDongCuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnh", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public byte[] HinhAnh
		{
			get
			{
				return this._HinhAnh;
			}
			set
			{
				if ((this._HinhAnh != value))
				{
					this.OnHinhAnhChanging(value);
					this.SendPropertyChanging();
					this._HinhAnh = value;
					this.SendPropertyChanged("HinhAnh");
					this.OnHinhAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT_CuaHang", DbType="Char(12)")]
		public string SDT_CuaHang
		{
			get
			{
				return this._SDT_CuaHang;
			}
			set
			{
				if ((this._SDT_CuaHang != value))
				{
					this.OnSDT_CuaHangChanging(value);
					this.SendPropertyChanging();
					this._SDT_CuaHang = value;
					this.SendPropertyChanged("SDT_CuaHang");
					this.OnSDT_CuaHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNhom", DbType="NVarChar(50)")]
		public string TenNhom
		{
			get
			{
				return this._TenNhom;
			}
			set
			{
				if ((this._TenNhom != value))
				{
					this.OnTenNhomChanging(value);
					this.SendPropertyChanging();
					this._TenNhom = value;
					this.SendPropertyChanged("TenNhom");
					this.OnTenNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CuaHang_DanhGia", Storage="_DanhGias", ThisKey="ID_CuaHang", OtherKey="ID_CuaHang")]
		internal EntitySet<DanhGia> DanhGias
		{
			get
			{
				return this._DanhGias;
			}
			set
			{
				this._DanhGias.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CuaHang_DichVu", Storage="_DichVus", ThisKey="ID_CuaHang", OtherKey="ID_CuaHang")]
		internal EntitySet<DichVu> DichVus
		{
			get
			{
				return this._DichVus;
			}
			set
			{
				this._DichVus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CuaHang_Menu", Storage="_Menus", ThisKey="ID_CuaHang", OtherKey="ID_CuaHang")]
		internal EntitySet<Menu> Menus
		{
			get
			{
				return this._Menus;
			}
			set
			{
				this._Menus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CuaHang_YeuThich", Storage="_YeuThiches", ThisKey="ID_CuaHang", OtherKey="ID_CuaHang")]
		internal EntitySet<YeuThich> YeuThiches
		{
			get
			{
				return this._YeuThiches;
			}
			set
			{
				this._YeuThiches.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CuaHang_ViTri", Storage="_ViTri", ThisKey="ID_CuaHang", OtherKey="ID", IsUnique=true, IsForeignKey=false)]
		internal ViTri ViTri
		{
			get
			{
				return this._ViTri.Entity;
			}
			set
			{
				ViTri previousValue = this._ViTri.Entity;
				if (((previousValue != value) 
							|| (this._ViTri.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ViTri.Entity = null;
						previousValue.CuaHang = null;
					}
					this._ViTri.Entity = value;
					if ((value != null))
					{
						value.CuaHang = this;
					}
					this.SendPropertyChanged("ViTri");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DanhGias(DanhGia entity)
		{
			this.SendPropertyChanging();
			entity.CuaHang = this;
		}
		
		private void detach_DanhGias(DanhGia entity)
		{
			this.SendPropertyChanging();
			entity.CuaHang = null;
		}
		
		private void attach_DichVus(DichVu entity)
		{
			this.SendPropertyChanging();
			entity.CuaHang = this;
		}
		
		private void detach_DichVus(DichVu entity)
		{
			this.SendPropertyChanging();
			entity.CuaHang = null;
		}
		
		private void attach_Menus(Menu entity)
		{
			this.SendPropertyChanging();
			entity.CuaHang = this;
		}
		
		private void detach_Menus(Menu entity)
		{
			this.SendPropertyChanging();
			entity.CuaHang = null;
		}
		
		private void attach_YeuThiches(YeuThich entity)
		{
			this.SendPropertyChanging();
			entity.CuaHang = this;
		}
		
		private void detach_YeuThiches(YeuThich entity)
		{
			this.SendPropertyChanging();
			entity.CuaHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DanhGia")]
	public partial class DanhGia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_User;
		
		private int _ID_CuaHang;
		
		private string _XepLoai;
		
		private EntityRef<CuaHang> _CuaHang;
		
		private EntityRef<FoodN_User> _FoodN_User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_UserChanging(int value);
    partial void OnID_UserChanged();
    partial void OnID_CuaHangChanging(int value);
    partial void OnID_CuaHangChanged();
    partial void OnXepLoaiChanging(string value);
    partial void OnXepLoaiChanged();
    #endregion
		
		public DanhGia()
		{
			this._CuaHang = default(EntityRef<CuaHang>);
			this._FoodN_User = default(EntityRef<FoodN_User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_User", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_User
		{
			get
			{
				return this._ID_User;
			}
			set
			{
				if ((this._ID_User != value))
				{
					if (this._FoodN_User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_UserChanging(value);
					this.SendPropertyChanging();
					this._ID_User = value;
					this.SendPropertyChanged("ID_User");
					this.OnID_UserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CuaHang", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_CuaHang
		{
			get
			{
				return this._ID_CuaHang;
			}
			set
			{
				if ((this._ID_CuaHang != value))
				{
					if (this._CuaHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_CuaHangChanging(value);
					this.SendPropertyChanging();
					this._ID_CuaHang = value;
					this.SendPropertyChanged("ID_CuaHang");
					this.OnID_CuaHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XepLoai", DbType="NVarChar(50)")]
		public string XepLoai
		{
			get
			{
				return this._XepLoai;
			}
			set
			{
				if ((this._XepLoai != value))
				{
					this.OnXepLoaiChanging(value);
					this.SendPropertyChanging();
					this._XepLoai = value;
					this.SendPropertyChanged("XepLoai");
					this.OnXepLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CuaHang_DanhGia", Storage="_CuaHang", ThisKey="ID_CuaHang", OtherKey="ID_CuaHang", IsForeignKey=true)]
		public CuaHang CuaHang
		{
			get
			{
				return this._CuaHang.Entity;
			}
			set
			{
				CuaHang previousValue = this._CuaHang.Entity;
				if (((previousValue != value) 
							|| (this._CuaHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CuaHang.Entity = null;
						previousValue.DanhGias.Remove(this);
					}
					this._CuaHang.Entity = value;
					if ((value != null))
					{
						value.DanhGias.Add(this);
						this._ID_CuaHang = value.ID_CuaHang;
					}
					else
					{
						this._ID_CuaHang = default(int);
					}
					this.SendPropertyChanged("CuaHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FoodN_User_DanhGia", Storage="_FoodN_User", ThisKey="ID_User", OtherKey="ID_User", IsForeignKey=true)]
		public FoodN_User FoodN_User
		{
			get
			{
				return this._FoodN_User.Entity;
			}
			set
			{
				FoodN_User previousValue = this._FoodN_User.Entity;
				if (((previousValue != value) 
							|| (this._FoodN_User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._FoodN_User.Entity = null;
						previousValue.DanhGias.Remove(this);
					}
					this._FoodN_User.Entity = value;
					if ((value != null))
					{
						value.DanhGias.Add(this);
						this._ID_User = value.ID_User;
					}
					else
					{
						this._ID_User = default(int);
					}
					this.SendPropertyChanged("FoodN_User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DichVu")]
	public partial class DichVu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_CuaHang;
		
		private int _ID_DichVu;
		
		private EntityRef<CuaHang> _CuaHang;
		
		private EntityRef<ChiTietDichVu> _ChiTietDichVu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_CuaHangChanging(int value);
    partial void OnID_CuaHangChanged();
    partial void OnID_DichVuChanging(int value);
    partial void OnID_DichVuChanged();
    #endregion
		
		public DichVu()
		{
			this._CuaHang = default(EntityRef<CuaHang>);
			this._ChiTietDichVu = default(EntityRef<ChiTietDichVu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CuaHang", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_CuaHang
		{
			get
			{
				return this._ID_CuaHang;
			}
			set
			{
				if ((this._ID_CuaHang != value))
				{
					if (this._CuaHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_CuaHangChanging(value);
					this.SendPropertyChanging();
					this._ID_CuaHang = value;
					this.SendPropertyChanged("ID_CuaHang");
					this.OnID_CuaHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DichVu", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_DichVu
		{
			get
			{
				return this._ID_DichVu;
			}
			set
			{
				if ((this._ID_DichVu != value))
				{
					if (this._ChiTietDichVu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_DichVuChanging(value);
					this.SendPropertyChanging();
					this._ID_DichVu = value;
					this.SendPropertyChanged("ID_DichVu");
					this.OnID_DichVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CuaHang_DichVu", Storage="_CuaHang", ThisKey="ID_CuaHang", OtherKey="ID_CuaHang", IsForeignKey=true)]
		public CuaHang CuaHang
		{
			get
			{
				return this._CuaHang.Entity;
			}
			set
			{
				CuaHang previousValue = this._CuaHang.Entity;
				if (((previousValue != value) 
							|| (this._CuaHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CuaHang.Entity = null;
						previousValue.DichVus.Remove(this);
					}
					this._CuaHang.Entity = value;
					if ((value != null))
					{
						value.DichVus.Add(this);
						this._ID_CuaHang = value.ID_CuaHang;
					}
					else
					{
						this._ID_CuaHang = default(int);
					}
					this.SendPropertyChanged("CuaHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChiTietDichVu_DichVu", Storage="_ChiTietDichVu", ThisKey="ID_DichVu", OtherKey="ID_DichVu", IsForeignKey=true)]
		public ChiTietDichVu ChiTietDichVu
		{
			get
			{
				return this._ChiTietDichVu.Entity;
			}
			set
			{
				ChiTietDichVu previousValue = this._ChiTietDichVu.Entity;
				if (((previousValue != value) 
							|| (this._ChiTietDichVu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ChiTietDichVu.Entity = null;
						previousValue.DichVus.Remove(this);
					}
					this._ChiTietDichVu.Entity = value;
					if ((value != null))
					{
						value.DichVus.Add(this);
						this._ID_DichVu = value.ID_DichVu;
					}
					else
					{
						this._ID_DichVu = default(int);
					}
					this.SendPropertyChanged("ChiTietDichVu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FoodN_User")]
	public partial class FoodN_User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_User;
		
		private string _HoTen;
		
		private string _SDT_User;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private System.Nullable<bool> _GioiTinh;
		
		private string _MatKhau;
		
		private System.Data.Linq.Binary _Avatar;
		
		private EntitySet<DanhGia> _DanhGias;
		
		private EntitySet<YeuThich> _YeuThiches;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_UserChanging(int value);
    partial void OnID_UserChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnSDT_UserChanging(string value);
    partial void OnSDT_UserChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnGioiTinhChanging(System.Nullable<bool> value);
    partial void OnGioiTinhChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnAvatarChanging(System.Data.Linq.Binary value);
    partial void OnAvatarChanged();
    #endregion
		
		public FoodN_User()
		{
			this._DanhGias = new EntitySet<DanhGia>(new Action<DanhGia>(this.attach_DanhGias), new Action<DanhGia>(this.detach_DanhGias));
			this._YeuThiches = new EntitySet<YeuThich>(new Action<YeuThich>(this.attach_YeuThiches), new Action<YeuThich>(this.detach_YeuThiches));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_User", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_User
		{
			get
			{
				return this._ID_User;
			}
			set
			{
				if ((this._ID_User != value))
				{
					this.OnID_UserChanging(value);
					this.SendPropertyChanging();
					this._ID_User = value;
					this.SendPropertyChanged("ID_User");
					this.OnID_UserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT_User", DbType="Char(12)")]
		public string SDT_User
		{
			get
			{
				return this._SDT_User;
			}
			set
			{
				if ((this._SDT_User != value))
				{
					this.OnSDT_UserChanging(value);
					this.SendPropertyChanging();
					this._SDT_User = value;
					this.SendPropertyChanged("SDT_User");
					this.OnSDT_UserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="Bit")]
		public System.Nullable<bool> GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="Char(40)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Avatar", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Avatar
		{
			get
			{
				return this._Avatar;
			}
			set
			{
				if ((this._Avatar != value))
				{
					this.OnAvatarChanging(value);
					this.SendPropertyChanging();
					this._Avatar = value;
					this.SendPropertyChanged("Avatar");
					this.OnAvatarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FoodN_User_DanhGia", Storage="_DanhGias", ThisKey="ID_User", OtherKey="ID_User")]
		internal EntitySet<DanhGia> DanhGias
		{
			get
			{
				return this._DanhGias;
			}
			set
			{
				this._DanhGias.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FoodN_User_YeuThich", Storage="_YeuThiches", ThisKey="ID_User", OtherKey="ID_User")]
		internal EntitySet<YeuThich> YeuThiches
		{
			get
			{
				return this._YeuThiches;
			}
			set
			{
				this._YeuThiches.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DanhGias(DanhGia entity)
		{
			this.SendPropertyChanging();
			entity.FoodN_User = this;
		}
		
		private void detach_DanhGias(DanhGia entity)
		{
			this.SendPropertyChanging();
			entity.FoodN_User = null;
		}
		
		private void attach_YeuThiches(YeuThich entity)
		{
			this.SendPropertyChanging();
			entity.FoodN_User = this;
		}
		
		private void detach_YeuThiches(YeuThich entity)
		{
			this.SendPropertyChanging();
			entity.FoodN_User = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Menu")]
	public partial class Menu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Menu;
		
		private int _ID_CuaHang;
		
		private System.Data.Linq.Binary _HinhAnhMenu;
		
		private EntityRef<CuaHang> _CuaHang;
		
		private EntityRef<MonAn> _MonAn;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_MenuChanging(int value);
    partial void OnID_MenuChanged();
    partial void OnID_CuaHangChanging(int value);
    partial void OnID_CuaHangChanged();
    partial void OnHinhAnhMenuChanging(System.Data.Linq.Binary value);
    partial void OnHinhAnhMenuChanged();
    #endregion
		
		public Menu()
		{
			this._CuaHang = default(EntityRef<CuaHang>);
			this._MonAn = default(EntityRef<MonAn>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Menu", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Menu
		{
			get
			{
				return this._ID_Menu;
			}
			set
			{
				if ((this._ID_Menu != value))
				{
					if (this._MonAn.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_MenuChanging(value);
					this.SendPropertyChanging();
					this._ID_Menu = value;
					this.SendPropertyChanged("ID_Menu");
					this.OnID_MenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CuaHang", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_CuaHang
		{
			get
			{
				return this._ID_CuaHang;
			}
			set
			{
				if ((this._ID_CuaHang != value))
				{
					if (this._CuaHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_CuaHangChanging(value);
					this.SendPropertyChanging();
					this._ID_CuaHang = value;
					this.SendPropertyChanged("ID_CuaHang");
					this.OnID_CuaHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnhMenu", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary HinhAnhMenu
		{
			get
			{
				return this._HinhAnhMenu;
			}
			set
			{
				if ((this._HinhAnhMenu != value))
				{
					this.OnHinhAnhMenuChanging(value);
					this.SendPropertyChanging();
					this._HinhAnhMenu = value;
					this.SendPropertyChanged("HinhAnhMenu");
					this.OnHinhAnhMenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CuaHang_Menu", Storage="_CuaHang", ThisKey="ID_CuaHang", OtherKey="ID_CuaHang", IsForeignKey=true)]
		public CuaHang CuaHang
		{
			get
			{
				return this._CuaHang.Entity;
			}
			set
			{
				CuaHang previousValue = this._CuaHang.Entity;
				if (((previousValue != value) 
							|| (this._CuaHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CuaHang.Entity = null;
						previousValue.Menus.Remove(this);
					}
					this._CuaHang.Entity = value;
					if ((value != null))
					{
						value.Menus.Add(this);
						this._ID_CuaHang = value.ID_CuaHang;
					}
					else
					{
						this._ID_CuaHang = default(int);
					}
					this.SendPropertyChanged("CuaHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MonAn_Menu", Storage="_MonAn", ThisKey="ID_Menu", OtherKey="ID_Menu", IsForeignKey=true)]
		public MonAn MonAn
		{
			get
			{
				return this._MonAn.Entity;
			}
			set
			{
				MonAn previousValue = this._MonAn.Entity;
				if (((previousValue != value) 
							|| (this._MonAn.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MonAn.Entity = null;
						previousValue.Menus.Remove(this);
					}
					this._MonAn.Entity = value;
					if ((value != null))
					{
						value.Menus.Add(this);
						this._ID_Menu = value.ID_Menu;
					}
					else
					{
						this._ID_Menu = default(int);
					}
					this.SendPropertyChanged("MonAn");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MonAn")]
	public partial class MonAn : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Menu;
		
		private string _TenMon;
		
		private System.Nullable<int> _Gia;
		
		private System.Data.Linq.Binary _HinhAnhMonAn;
		
		private string _Muc;
		
		private EntitySet<Menu> _Menus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_MenuChanging(int value);
    partial void OnID_MenuChanged();
    partial void OnTenMonChanging(string value);
    partial void OnTenMonChanged();
    partial void OnGiaChanging(System.Nullable<int> value);
    partial void OnGiaChanged();
    partial void OnHinhAnhMonAnChanging(System.Data.Linq.Binary value);
    partial void OnHinhAnhMonAnChanged();
    partial void OnMucChanging(string value);
    partial void OnMucChanged();
    #endregion
		
		public MonAn()
		{
			this._Menus = new EntitySet<Menu>(new Action<Menu>(this.attach_Menus), new Action<Menu>(this.detach_Menus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Menu", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Menu
		{
			get
			{
				return this._ID_Menu;
			}
			set
			{
				if ((this._ID_Menu != value))
				{
					this.OnID_MenuChanging(value);
					this.SendPropertyChanging();
					this._ID_Menu = value;
					this.SendPropertyChanged("ID_Menu");
					this.OnID_MenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenMon", DbType="NVarChar(50)")]
		public string TenMon
		{
			get
			{
				return this._TenMon;
			}
			set
			{
				if ((this._TenMon != value))
				{
					this.OnTenMonChanging(value);
					this.SendPropertyChanging();
					this._TenMon = value;
					this.SendPropertyChanged("TenMon");
					this.OnTenMonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="Int")]
		public System.Nullable<int> Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnhMonAn", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary HinhAnhMonAn
		{
			get
			{
				return this._HinhAnhMonAn;
			}
			set
			{
				if ((this._HinhAnhMonAn != value))
				{
					this.OnHinhAnhMonAnChanging(value);
					this.SendPropertyChanging();
					this._HinhAnhMonAn = value;
					this.SendPropertyChanged("HinhAnhMonAn");
					this.OnHinhAnhMonAnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Muc", DbType="NVarChar(50)")]
		public string Muc
		{
			get
			{
				return this._Muc;
			}
			set
			{
				if ((this._Muc != value))
				{
					this.OnMucChanging(value);
					this.SendPropertyChanging();
					this._Muc = value;
					this.SendPropertyChanged("Muc");
					this.OnMucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MonAn_Menu", Storage="_Menus", ThisKey="ID_Menu", OtherKey="ID_Menu")]
		internal EntitySet<Menu> Menus
		{
			get
			{
				return this._Menus;
			}
			set
			{
				this._Menus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Menus(Menu entity)
		{
			this.SendPropertyChanging();
			entity.MonAn = this;
		}
		
		private void detach_Menus(Menu entity)
		{
			this.SendPropertyChanging();
			entity.MonAn = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.YeuThich")]
	public partial class YeuThich : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_User;
		
		private int _ID_CuaHang;
		
		private EntityRef<CuaHang> _CuaHang;
		
		private EntityRef<FoodN_User> _FoodN_User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_UserChanging(int value);
    partial void OnID_UserChanged();
    partial void OnID_CuaHangChanging(int value);
    partial void OnID_CuaHangChanged();
    #endregion
		
		public YeuThich()
		{
			this._CuaHang = default(EntityRef<CuaHang>);
			this._FoodN_User = default(EntityRef<FoodN_User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_User", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_User
		{
			get
			{
				return this._ID_User;
			}
			set
			{
				if ((this._ID_User != value))
				{
					if (this._FoodN_User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_UserChanging(value);
					this.SendPropertyChanging();
					this._ID_User = value;
					this.SendPropertyChanged("ID_User");
					this.OnID_UserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CuaHang", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_CuaHang
		{
			get
			{
				return this._ID_CuaHang;
			}
			set
			{
				if ((this._ID_CuaHang != value))
				{
					if (this._CuaHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_CuaHangChanging(value);
					this.SendPropertyChanging();
					this._ID_CuaHang = value;
					this.SendPropertyChanged("ID_CuaHang");
					this.OnID_CuaHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CuaHang_YeuThich", Storage="_CuaHang", ThisKey="ID_CuaHang", OtherKey="ID_CuaHang", IsForeignKey=true)]
		public CuaHang CuaHang
		{
			get
			{
				return this._CuaHang.Entity;
			}
			set
			{
				CuaHang previousValue = this._CuaHang.Entity;
				if (((previousValue != value) 
							|| (this._CuaHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CuaHang.Entity = null;
						previousValue.YeuThiches.Remove(this);
					}
					this._CuaHang.Entity = value;
					if ((value != null))
					{
						value.YeuThiches.Add(this);
						this._ID_CuaHang = value.ID_CuaHang;
					}
					else
					{
						this._ID_CuaHang = default(int);
					}
					this.SendPropertyChanged("CuaHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FoodN_User_YeuThich", Storage="_FoodN_User", ThisKey="ID_User", OtherKey="ID_User", IsForeignKey=true)]
		public FoodN_User FoodN_User
		{
			get
			{
				return this._FoodN_User.Entity;
			}
			set
			{
				FoodN_User previousValue = this._FoodN_User.Entity;
				if (((previousValue != value) 
							|| (this._FoodN_User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._FoodN_User.Entity = null;
						previousValue.YeuThiches.Remove(this);
					}
					this._FoodN_User.Entity = value;
					if ((value != null))
					{
						value.YeuThiches.Add(this);
						this._ID_User = value.ID_User;
					}
					else
					{
						this._ID_User = default(int);
					}
					this.SendPropertyChanged("FoodN_User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ViTri")]
	public partial class ViTri : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<double> _HoanhDo;
		
		private System.Nullable<double> _TungDo;
		
		private EntityRef<CuaHang> _CuaHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnHoanhDoChanging(System.Nullable<double> value);
    partial void OnHoanhDoChanged();
    partial void OnTungDoChanging(System.Nullable<double> value);
    partial void OnTungDoChanged();
    #endregion
		
		public ViTri()
		{
			this._CuaHang = default(EntityRef<CuaHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					if (this._CuaHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoanhDo", DbType="Float")]
		public System.Nullable<double> HoanhDo
		{
			get
			{
				return this._HoanhDo;
			}
			set
			{
				if ((this._HoanhDo != value))
				{
					this.OnHoanhDoChanging(value);
					this.SendPropertyChanging();
					this._HoanhDo = value;
					this.SendPropertyChanged("HoanhDo");
					this.OnHoanhDoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TungDo", DbType="Float")]
		public System.Nullable<double> TungDo
		{
			get
			{
				return this._TungDo;
			}
			set
			{
				if ((this._TungDo != value))
				{
					this.OnTungDoChanging(value);
					this.SendPropertyChanging();
					this._TungDo = value;
					this.SendPropertyChanged("TungDo");
					this.OnTungDoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CuaHang_ViTri", Storage="_CuaHang", ThisKey="ID", OtherKey="ID_CuaHang", IsForeignKey=true)]
		public CuaHang CuaHang
		{
			get
			{
				return this._CuaHang.Entity;
			}
			set
			{
				CuaHang previousValue = this._CuaHang.Entity;
				if (((previousValue != value) 
							|| (this._CuaHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CuaHang.Entity = null;
						previousValue.ViTri = null;
					}
					this._CuaHang.Entity = value;
					if ((value != null))
					{
						value.ViTri = this;
						this._ID = value.ID_CuaHang;
					}
					else
					{
						this._ID = default(int);
					}
					this.SendPropertyChanged("CuaHang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
